spring:
  application:
    name: e-book-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book-product?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://dpb:123456@eureka1:8761/eureka/,http://dpb:123456@eureka2:8761/eureka/